name: foodly_world
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  animated_bottom_navigation_bar: ^1.3.3
  animate_do: ^3.3.4
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  clay_containers: ^0.3.4
  cupertino_icons: ^1.0.2
  dio: ^5.5.0+1
  fab_circular_menu_plus: ^0.0.2
  flex_color_scheme: ^7.3.1
  flutter_bloc: ^8.1.6
  flutter_image_slideshow: ^0.1.6
  flutter_native_splash: ^2.4.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  geolocator: ^12.0.0
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.7.0
  google_sign_in: ^6.2.1
  go_router: ^14.2.1
  gusto_neumorphic: ^3.3.0
  hydrated_bloc: ^9.1.4
  icons_launcher: ^2.1.7
  icons_plus: ^5.0.0
  image_cropper: ^7.1.0
  image_picker: ^1.1.1
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  json_annotation: ^4.9.0
  local_auth: ^2.2.0
  logger: ^2.3.0
  nova_places_autocomplete: ^2.0.0
  path_provider: ^2.1.2
  responsive_framework: ^1.1.1
  retrofit: ">=4.0.0 <5.0.0"
  shared_preferences: ^2.2.3
  sidebarx: ^0.17.1
  toggle_switch: ^2.3.0
  universal_io: ^2.2.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  intl_utils: ^2.8.7
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.1

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/mocks/menu.json

flutter_intl:
  enabled: true
