// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzQazJMQpIBXLz3tJYfBhAxMKnYBtP58U',
    appId: '1:275754925527:web:caccc645a30be3afa71f92',
    messagingSenderId: '275754925527',
    projectId: 'foodly-solutions',
    authDomain: 'foodly-solutions.firebaseapp.com',
    storageBucket: 'foodly-solutions.firebasestorage.app',
    measurementId: 'G-7SF6YSF7PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZcjWJNl6EWgWLLAnoB-5ma653ysEJ8gg',
    appId: '1:275754925527:android:4e4a035d1c752c7ba71f92',
    messagingSenderId: '275754925527',
    projectId: 'foodly-solutions',
    storageBucket: 'foodly-solutions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeVxMOCJA25C30pRKEatHq-2HcaIRWgCw',
    appId: '1:275754925527:ios:bbbd9b4c6e8854e7a71f92',
    messagingSenderId: '275754925527',
    projectId: 'foodly-solutions',
    storageBucket: 'foodly-solutions.firebasestorage.app',
    androidClientId: '275754925527-b6b5bume1ljmn2e723mvifp26cf73hoh.apps.googleusercontent.com',
    iosClientId: '275754925527-bm3d1di90qvct31m1ltbvc5nnash0bjg.apps.googleusercontent.com',
    iosBundleId: 'com.foodlysolutions.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeVxMOCJA25C30pRKEatHq-2HcaIRWgCw',
    appId: '1:275754925527:ios:bbbd9b4c6e8854e7a71f92',
    messagingSenderId: '275754925527',
    projectId: 'foodly-solutions',
    storageBucket: 'foodly-solutions.firebasestorage.app',
    androidClientId: '275754925527-b6b5bume1ljmn2e723mvifp26cf73hoh.apps.googleusercontent.com',
    iosClientId: '275754925527-bm3d1di90qvct31m1ltbvc5nnash0bjg.apps.googleusercontent.com',
    iosBundleId: 'com.foodlysolutions.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzQazJMQpIBXLz3tJYfBhAxMKnYBtP58U',
    appId: '1:275754925527:web:d5b5649ecb76339ba71f92',
    messagingSenderId: '275754925527',
    projectId: 'foodly-solutions',
    authDomain: 'foodly-solutions.firebaseapp.com',
    storageBucket: 'foodly-solutions.firebasestorage.app',
    measurementId: 'G-XERW9H3W8H',
  );

}