// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo6O6EOWhYoyiVgO6TmJvki09U4cQBDc8',
    appId: '1:951890938827:web:47dc682e6476d1ed8f044e',
    messagingSenderId: '951890938827',
    projectId: 'apps-369',
    authDomain: 'apps-369.firebaseapp.com',
    storageBucket: 'apps-369.firebasestorage.app',
    measurementId: 'G-HK9C5PPPFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2EUJDudKf-67bKDrpGeGJfKxYjmlMSL4',
    appId: '1:951890938827:android:8a8a42d77aefe8ee8f044e',
    messagingSenderId: '951890938827',
    projectId: 'apps-369',
    storageBucket: 'apps-369.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjOEscriIGOl3RtyhUjZwfcc2kOdqsbxA',
    appId: '1:951890938827:ios:49b0cb3813b687208f044e',
    messagingSenderId: '951890938827',
    projectId: 'apps-369',
    storageBucket: 'apps-369.firebasestorage.app',
    androidClientId: '951890938827-7635tf8epn103l226oo2el998f4i019t.apps.googleusercontent.com',
    iosClientId: '951890938827-2hgpslnumba6gmm17ainu8flp4q5ctl4.apps.googleusercontent.com',
    iosBundleId: 'com.foodlysolutions.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjOEscriIGOl3RtyhUjZwfcc2kOdqsbxA',
    appId: '1:951890938827:ios:49b0cb3813b687208f044e',
    messagingSenderId: '951890938827',
    projectId: 'apps-369',
    storageBucket: 'apps-369.firebasestorage.app',
    androidClientId: '951890938827-7635tf8epn103l226oo2el998f4i019t.apps.googleusercontent.com',
    iosClientId: '951890938827-2hgpslnumba6gmm17ainu8flp4q5ctl4.apps.googleusercontent.com',
    iosBundleId: 'com.foodlysolutions.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo6O6EOWhYoyiVgO6TmJvki09U4cQBDc8',
    appId: '1:951890938827:web:1dc08f395d416ed68f044e',
    messagingSenderId: '951890938827',
    projectId: 'apps-369',
    authDomain: 'apps-369.firebaseapp.com',
    storageBucket: 'apps-369.firebasestorage.app',
    measurementId: 'G-HKGX3MXJJK',
  );

}